### PR TITLE
Add transaction hashes to relevant governance events

### PR DESCRIPTION
**Pull request by pedropregueiro**
Useful for nouns clients to link to the specific transaction on-chain.

### CODE REVIEW

**Comment by eladmallel** [comment]
good one @pedropregueiro

**Comment by davidbrai** [comment]
@pedropregueiro I've pushed this branch here: https://api.goldsky.com/api/public/project_cldf2o9pqagp43svvbk5u3kmo/subgraphs/nouns/0.2.7/gn

take a look please. if it looks good to you I can promote it to be the "prod" subgraph

**Comment by pedropregueiro** [comment]
> @pedropregueiro I've pushed this branch here: https://api.goldsky.com/api/public/project_cldf2o9pqagp43svvbk5u3kmo/subgraphs/nouns/0.2.7/gn
> 
> take a look please. if it looks good to you I can promote it to be the "prod" subgraph

thanks @davidbrai! I did test it with camp's graph endpoints, but if you deploy the latest version - [d8fbd8c](https://github.com/nounsDAO/nouns-monorepo/pull/856/commits/d8fbd8c1d505d6eaeece484673bd96df75f6f143) - I can point camp to that graph and test again.

**Comment by davidbrai** [comment]
@pedropregueiro I've just updated it, try now

https://api.goldsky.com/api/public/project_cldf2o9pqagp43svvbk5u3kmo/subgraphs/nouns/0.2.7/gn

**Comment by pedropregueiro** [comment]
yep, seems to all be working as expected!

**Review by davidbrai — APPROVED** [review]

**Pull request merged**
