### PR TITLE
Add 404 page

### PR DESCRIPTION
**Pull request by bcjgit**
## TLDR

After hitting an undefined route (due to a typo on my part) and wondering why the page was seemingly hanging for ~1 min I realized there is no "catch all" route equivalent to a 404 page in the `nouns-webapp`.  I've added one here. 

## Verification

Screen Shot 2021-09-15 at 7 24 04 PM

### CODE REVIEW

**Comment by bcjgit** [comment]
Open to any and all feedback. Not sure what processes / styles etc. you folks normally follow. On top of that, relatively new to react (more of backend guy by trade) so open to feedback there as well.

Thanks!

**Comment by cryptoseneca** [comment]
Hey @bcjgit. Thanks for pointing this out! Your work looks great - all is well implemented. I added just a few finishing touches to make sure the `Footer` appears at the bottom of parent + added some Nounish art by @gremplin. Check out the PR: [](https://github.com/bcjgit/nouns-monorepo/pull/1).

If it looks good to you, feel free to merge that in and I will then proceed to merge this PR in as well.

**Comment by bcjgit** [comment]
Thanks for taking a look @cryptoseneca! Which PR are you referring to re `Footer` and Nounish art (super excited for that addition by the way)?  I looked at the open PRs didn't see anything that matched that description (maybe https://github.com/nounsDAO/nouns-monorepo/pull/232 ?). 

Thanks!

**Comment by cryptoseneca** [comment]
I should have linked it. It's here: https://github.com/bcjgit/nouns-monorepo/pull/1

**Comment by bcjgit** [comment]
@cryptoseneca merged your PR and updated `..` => `...`!

**Review by cryptoseneca — APPROVED** [review]

**Pull request merged**
